### ISSUE TITLE
how to add image in opensearch plugin

### ISSUE THREAD

**Issue by daros21** [garyforsterio/gatsby-plugin-opensearch#2]
Hi, 
according https://developer.mozilla.org/en-US/docs/Web/OpenSearch, I'd like to add an image to my opensearch.
I've tried with adding javascript object to plugin options (in gatsby-config.js file):
Image: {
            _width: "16",
            _height: "16",
            _type:"image/x-icon",
            __text: "https://example.se/favicon.ico"
            },
but this is not transfered to opensearch.xml file.
if i am doing it in wrong way, please could you show me how to add an image to opensearch?

**Comment by garyforsterio** [comment]
Hi @daros21 apologies for the very late response. I've now added a new option to specify the image in version 1.4.0 and added some documentation [here|https://github.com/garyforsterio/gatsby-plugin-opensearch#options], let me know if you have any issues 🙂

**Comment by daros21** [comment]
Hi Gary,
I think I can close this issue now. 
Thank you for adding this option.
